### ISSUE TITLE
[Backend] Business Logic Layer - Groups

### ISSUE THREAD

**Issue by RomanYanchuk** [Programming-Engineering-Pmi-33/ProjectReporter#6]
## Опис
* Відповідно до створеної wiki-сторінки реалізувати бізнес логіку для наступного функціоналу:

- [x] Створення `групи`.
- [x] Додавання `CoOwner`.
- [x] Створення запрошень (для `академічної групи` / по `Id` користувачів).
- [x] Редагування `description`, `status`, `gitLink` (зміна даних групи, **виключно** для `Owner`, `CoOwner`).
- [x] Приймання `запрошень `для користувачів (по `GUID` і `Id` користувача).
- [x] Створення `проектів`.
- [x] Додавання `користувачів` до `проектів`.
- [x] Редагування полів `проектів `(**тільки** його `учасники`).
- [x] Створення `тасок`.
- [x] Зміна умов `тасок `(зміна **виключно** для `Owner`, `CoOwner`).
- [x] Створення `репортів`.
- [x] Зміна `репортів ` (для **не оцінених**, **не можна** змінювати `Points`).
- [x] Оцінювання репорта (виключно `Owner`).

**Comment by RomanYanchuk** [comment]
## Додані додаткові методи:
* Отримування груп, проектів, тасок, репортів.

**Comment by RomanYanchuk** [comment]
## TODO:

- [x]  GetGroupMembers, GetProjectMembers.

- [x] Validation.

- [x]  UsersService Faculty/Department logic (+txt files).
